# This file can be used by client applications to link
# this library: before using "XXX_LNK" please call the
# "xxx_compile" target.

ifndef MAKEFILENETLIB
MAKEFILENETLIB=.

# Dependencies
include $(ADOPT_LIB)/makefile.logger

NETLIB_COMPILE = $(call test_uptodate,$(ADOPT_LIB),netlib.a,do_netlib)

do_netlib:
	$(Q)$(MAKE) $(MAKEOPTS) -C $(ADOPT_LIB) netlib.a

NETLIB_LNK = $(ADOPT_LIB)/netlib.a $(LOGGER_LNK) -lstdc++

endif
