# This file can be used by client applications to link
# this library: before using "XXX_LNK" please call the
# "xxx_compile" target.

ifndef MAKEFILEIOLIB
MAKEFILEIOLIB=.

IOLIB_COMPILE = $(call test_uptodate,$(ADOPT_LIB),iolib.a,do_iolib)


do_iolib:
	$(Q)$(MAKE) $(MAKEOPTS) -C $(ADOPT_LIB) iolib.a

IOLIB_LNK = $(ADOPT_LIB)/iolib.a -lstdc++

endif

