# This file can be used by client applications to link
# this library: before using "XXX_LNK" please call the
# "xxx_compile" target.

ifndef MAKEFILEADSECDIAGNLIB
MAKEFILEADSECDIAGNLIB=.

# Dependencies
include $(ADOPT_LIB)/makefile.logger

ADSECDIAGNLIB_COMPILE = $(call test_uptodate,$(ADOPT_LIB),adsecdiagnlib.a,do_adsecdiagnlib)


do_adsecdiagnlib:
	$(Q)$(MAKE) $(MAKEOPTS) -C $(ADOPT_LIB) adsecdiagnlib.a

ADSECDIAGNLIB_LNK = $(ADOPT_LIB)/adsecdiagnlib.a $(LOGGER_LNK) -lstdc++

endif
