# This file can be used by client applications to link
# this library: before using "XXX_LNK" please call the
# "xxx_compile" target.

ifndef MAKEFILELOGGER
MAKEFILELOGGER=.

# Base lib export makefile
include $(ADOPT_LIB)/base/makefile.base

LOGGER_COMPILE = $(call test_uptodate,$(ADOPT_LIB),logger.a,do_logger) $(BASE_COMPILE)

do_logger:
	$(Q)$(MAKE) $(MAKEOPTS) -C $(ADOPT_LIB) logger.a

LOGGER_LNK = $(ADOPT_LIB)/logger.a $(THRDLIB_LNK) -lstdc++

endif
