# This file can be used by client applications to link
# this library: before using "XXX_LNK" please call the
# "xxx_compile" target.

# Supervisor general makefile
include $(ADOPT_SOURCE)/makefile.gen

# Dependencies
include $(ADOPT_LIB)/makefile.logger

netlib_compile:
	cd $(ADOPT_LIB); make netlib.a;

NETLIB_LNK = $(ADOPT_LIB)/netlib.a $(LOGGER_LNK) -lstdc++

