# This file can be used by client applications to link
# this library: before using "XXX_LNK" please call the
# "xxx_compile" target.

ifndef MAKEFILECONFIGLIB
MAKEFILECONFIGLIB=.

# Base lib export makefile
include $(ADOPT_LIB)/makefile.logger

CONFIGLIB_COMPILE = $(call test_uptodate,$(ADOPT_LIB),configlib.a,do_configlib) $(LOGGER_COMPILE)


do_configlib:
	$(Q)$(MAKE) $(MAKEOPTS) -C $(ADOPT_LIB) configlib.a

CONFIGLIB_LNK = $(ADOPT_LIB)/configlib.a -lstdc++ $(LOGGER_LNK)

endif
